export const STORE_USER = 'STORE_USER';
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const STORE_PURCHASE = 'STORE_PURCHASE';
export const CLEAR_PURCHASE = 'CLEAR_PURCHASE';

export const SHOW_SNACKBAR = 'SHOW_SNACKBAR';
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR';
export const EXIT_SNACKBAR = 'EXIT_SNACKBAR';

export const SET_PRODUCT = 'SET_PRODUCT';
export const SET_PRODUCT_QUANTITY = 'SET_PRODUCT_QUANTITY';
export const INCREMENT_PRODUCT = 'INCREMENT_PRODUCT';
export const DECREMENT_PRODUCT = 'DECREMENT_PRODUCT';

export const ADD_TO_CART = 'ADD_TO_CART';
export const ADD_QUANTITY = 'ADD_QUANTITY';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const SET_CART_QUANTITY = 'SET_CART_QUANTITY';
export const INCREMENT_CART_QUANTITY = 'INCREMENT_CART_QUANTITY';
export const DECREMENT_CART_QUANTITY = 'DECREMENT_CART_QUANTITY';
